apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmg-mongodb-express
spec:
  selector:
    matchLabels:
      app: mmg-mongodb-express
  template:
    metadata:
      labels:
        app: mmg-mongodb-express
    spec:
      containers:
      - name: mmg-mongo-express
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mmg-mongodb-secret
                key: mongodb-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mmg-mongodb-secret
                key: mongodb-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mmg-mongodb-configmap
                key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: mmg-mongodb-express-service
spec:
  selector:
    app: mmg-mongodb-express
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30000

